### ISSUE TITLE
"Settings not available in smi mode" only shows if started in smi mode

### ISSUE THREAD

**Issue by MattPainter01** [ethanwharris/gnome-nvidia-extension#145]
# Expected Behavior

Error message shown whenever settings button is clicked in smi mode

# Current Behavior

Error only shown if extension started in smi mode, not if it is switched to smi mode from other mode and then the button is clicked

**Comment by MattPainter01** [comment]
Perhaps the error should only be shown if we detect settings is not available and the button is clicked? Although in this case we may as well remove the button when we detect it is not available. 

It might still be useful to open settings using the button in smi mode.

**Comment by ethanwharris** [comment]
Closed with #142
