### ISSUE TITLE
Extension shows 10% gpu utilisation when the real usage is 100%

### ISSUE THREAD

**Issue by ChristianRomberg** [ethanwharris/gnome-nvidia-extension#147]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
The extension should show 100% utisation

# Current Behavior
It shows 100%

# Failure Information (for bugs)

Nothing

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install plugin
2. Run a program to fry your gpu
3. Look at the plugin

**Comment by ChristianRomberg** [comment]
I'm not 10% sure but I think this code is to blame: https://github.com/ethanwharris/gnome-nvidia-extension/blob/master/src/nvidiautil%40ethanwharris/settingsProperties.js#L30

**Comment by MattPainter01** [comment]
Hi @ChristianRomberg 

Could you confirm a couple of things for us:
- Are you on the latest version (master) from the github or the gnome extensions page?
- Which provider are you using in the extension settings?

We think this bug should have been fixed as of #146, so if you install from master it should work fine.

**Comment by ChristianRomberg** [comment]
Hi @MattPainter01 

I installed the latest version from the extensions page, which looks a lot different than what is currently on github.  I have not been able to reproduce the issue, I didn't get the GPU utilisation to rise to 100%. I'm gonna do some benchmarks when I get home. Thanks for your help!

**Comment by MattPainter01** [comment]
We're working to get the new version of the extension to pass the gnome extensions review process, for the moment the github master version is the best to use.
