### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ethanwharris** [ethanwharris/gnome-nvidia-extension#15]
Add a menu bar to allow the user to configure the extension. As a minimum, choose the handling mode for multiple GPUs (e.g. Average, Max?, Selected etc.). @MattPainter01 Unsure of how configuration should work? A click event could work but would stop it from opening nvidia settings.

**Comment by MattPainter01** [comment]
@ethanwharris 
How about:
Left Click - Open Nvidia settings
Right Click - Open config options

**Comment by ethanwharris** [comment]
Verdict: will use configuration xml to enable configuration from tweak tool.
