### ISSUE TITLE
Button Cleanup

### ISSUE THREAD

**Issue by derenv** [ethanwharris/gnome-nvidia-extension#178]
# Prerequisites

GNOME Shell 3.38.0
Listed as version 7 in metadata.json

# Expected Behavior

Proper display of buttons

# Current Behavior

Only shown as icons, looks strange

## Steps to Reproduce

init/restart gnome

## Context

* Nvidia-Settings Version: nvidia-settings: version 440.82
* Nvidia-smi version: NVIDIA System Management Interface -- v450.66
* Operating System: Ubuntu 20.10

## Failure Logs
(none)

**Comment by ethanwharris** [comment]
Closed by #179
