### ISSUE TITLE
GNOME extensions needs updated

### ISSUE THREAD

**Issue by derenv** [ethanwharris/gnome-nvidia-extension#180]
Is it possible to update the version available on [GNOME extensions](https://extensions.gnome.org/extension/1320/nvidia-gpu-stats-tool/)? The current version available is 7 (for gnome 3.36)

**Comment by ethanwharris** [comment]
Sure :smiley: I've submitted it to extensions.gnome.org, may take a few weeks to go live. You can check the status here: https://extensions.gnome.org/review/19928

I'll close this issue once it's up

**Comment by ethanwharris** [comment]
Looks like it's up now so closing this
