### ISSUE TITLE
Gtk.IconTheme.get_default() is null (wayland)

### ISSUE THREAD

**Issue by kenohassler** [ethanwharris/gnome-nvidia-extension#183]
I decided to test my patch again and stumbled upon an error that only occurs in Wayland sessions.
![null](https://user-images.githubusercontent.com/40292329/136850223-5af1acda-1261-4d5f-82c8-de7ed0ae0cd6.png)

# Expected Behavior

It should work regardless if the session is X.org or Wayland.

# Current Behavior

The extension is not loaded (see screenshot).

# Failure Information

The function is deprecated. The code snippet given here proposes a simple solution:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1997

## Context

Tested on Ubuntu 21.04 and 21.10.

**Comment by derenv** [comment]
Hi @kenohassler, i've also ran into this issue, go ahead and make a new PR for this.
