### ISSUE TITLE
Can't display the settings menu

### ISSUE THREAD

**Issue by FowlerMcCoi** [ethanwharris/gnome-nvidia-extension#188]
Error: No property border_width on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  buildPrefsWidget@/home/niko/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/prefs.js:153:14
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by AlfonsodRioss** [comment]
Hello! using this answer:
https://github.com/timbertson/gnome-shell-impatience/pull/24
And googling some of the new Gnome 40 standard I got it functioning, once I learn to publish this change (I'm new with github changes) I will make it available

**Comment by AlfonsodRioss** [comment]
I'm sorry I( didn't Realize that the problem was that I installed it from https://extensions.gnome.org/ the github version is alraedy corrected, principally the prefs.js file has the necesary changes.

**Comment by derenv** [comment]
that's okay! i need to look into updating the https://extensions.gnome.org/ version. I'll mark this as closed.
