### ISSUE TITLE
Updating gnome extensions website

### ISSUE THREAD

**Issue by derenv** [ethanwharris/gnome-nvidia-extension#189]
When the [wayland](https://github.com/ethanwharris/gnome-nvidia-extension/milestone/5) and [version 9](https://github.com/ethanwharris/gnome-nvidia-extension/milestone/4) milestones are reached, we need to upload the new version to the [gnome extensions](https://extensions.gnome.org/) website.

@ethanwharris what's the process for this?

**Comment by ethanwharris** [comment]
@derenv I think I have to upload a zip via this form: https://extensions.gnome.org/upload/ - if you make a release via github and ping me to upload the zip then I should be able to do it :smiley: ... if I can remember how haha

**Comment by derenv** [comment]
> @derenv I think I have to upload a zip via this form: https://extensions.gnome.org/upload/ - if you make a release via github and ping me to upload the zip then I should be able to do it :smiley: ... if I can remember how haha

ok doke!

**Comment by derenv** [comment]
Hi @ethanwharris, could you look at merging #196 and then building+uploading the zip? The current version on the gnome extensions website is incompatible with gnome 40.

If you aren't able to it may be worth someone else forking the project (not sure how that works with uploading to the gnome website, maybe a rename?).

**Comment by ethanwharris** [comment]
@derenv Hey, sorry for ghosting. I will try to do it this weekend! You are always free to fork if you think that would make things easier (it's a permissive license so that's always ok) but I think you would have to rename it. If you decide to go that route just let me know and I should be able to update the gnome extensions entry for this to point to the new one (from what I remember anyway). Thanks for all your work on this, the changes look great 😃

**Comment by derenv** [comment]
@ethanwharris thanks! Okay, it may make getting releases out easier but i probably won't fork unless we need to do a bunch of pull requests (so probably next gnome release lol). Thanks for the info on how to do so.

**Comment by ethanwharris** [comment]
@derenv I have submitted the new version to `extensions.gnome.org` (I think 😆 ). It's now in review, you should be able to see the statues here: https://extensions.gnome.org/review/31344

**Comment by derenv** [comment]
@ethanwharris thanks! Hope it's accepted soon.
