### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by derenv** [ethanwharris/gnome-nvidia-extension#197]
Now that work on v9.0 is pretty much finished, i think it would be a good idea to create some unit tests - hopefully allowing us to clean up any remaining bugs/inefficient code.

one possible method is to use the [jasmine testing framework](https://jasmine.github.io/) with the eslint plugin (eslint-plugin-jasmine) and adding jasmine/recommended to the eslint rulesets.

**Comment by kenohassler** [comment]
I'm not against unit testing, but I'm questioning if it is particularly useful for a shell extension. Since most of the code does UI manipulation in some way, how would we test it for correctness -- especially in a CI/CD pipeline without an NV GPU?
