### ISSUE TITLE
Version 9 Review

### ISSUE THREAD

**Issue by ethanwharris** [ethanwharris/gnome-nvidia-extension#199]
Our version 9 submission was rejected with the following comment:
```
1. You cannot create objects in `init()` (line 465 to 469 extension.js):
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#only-use-init-for-initialization
    Move everything to enable and null them out in disable.

2. Also null out `_menu` in disable (extension.js).

3. You cannot create objects in global scope which the same as init (line 11 to 17 gIcons.js).
    Create a function there that can create and return them.

If you need any help with your extension you can ask us on:
- [GNOME Matrix Channel](https://matrix.to/#/#extensions:gnome.org)
- IRC Bridge: irc://irc.gimpnet.org/shell-extensions
```

cc @derenv @kenohassler

**Comment by kenohassler** [comment]
Thanks for the heads-up! I'll have a look into it later this evening.

**Comment by kenohassler** [comment]
Alright, the issues should be fixed. The patch runs on my system now, but of course it has only seen minimal testing :grin:

**Comment by derenv** [comment]
Changes approved and merged, @ethanwharris can you tag as v9.1 and resubmit?

**Comment by derenv** [comment]
Before re-submission it's probably a good idea (re @kenohassler) to test on ubuntu 22.04 which uses gnome 42, should save us creating a second minor version.

**Comment by derenv** [comment]
should be dealt with as of #201 @ethanwharris

**Comment by kenohassler** [comment]
So, I finally managed to briefly test the extension on real hardware. As you can see, it runs as expected on ubuntu 22.04 :tada:

![screenshot_2204](https://user-images.githubusercontent.com/40292329/164785000-14a1d1d4-6635-4598-b005-fe2bf64db08e.png)

I think we're fine. If you agree @ethanwharris, we could re-submit what we have right now.

**Comment by ethanwharris** [comment]
Awesome! I'll make a submission tomorrow :smiley:

**Comment by ethanwharris** [comment]
Submitted 😃 I'll let you know when we get a response
