### ISSUE TITLE
Update README.md for X11 and Wayland instructions

### ISSUE THREAD

**Issue by derenv** [ethanwharris/gnome-nvidia-extension#202]
# Expected Behavior

We should have clear instructions that work with both X11 and Wayland systems, as Nvidia+Wayland systems are slowly becoming more viable. This should reduce the potential for user confusion (and probably issues for us to respond to) in future.

[for example, nvidia-settings is slowly getting working updates!](https://github.com/NVIDIA/nvidia-settings/issues/69#issuecomment-1120504355)

# Current Behavior

> ![Screenshot_20220615_161430](https://user-images.githubusercontent.com/35734401/173863467-9c12ed92-4b79-4fed-85b0-ebc6fb691813.png)

The shortcut mentioned here only functions on X11 systems, though for Wayland the only way to reload is to [logout and login again](https://askubuntu.com/questions/964068/when-will-wayland-support-restarting-the-shell-by-command), so i think only a minor modification to say that explicitly should be needed.

**Comment by derenv** [comment]
results of #212 will probably require a README rewrite, so can try to fit this in there.

**Comment by kenohassler** [comment]
closed in #214
