### ISSUE TITLE
No icons show

### ISSUE THREAD

**Issue by deppy-v2** [ethanwharris/gnome-nvidia-extension#208]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I am running the latest version
- [ Yes] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting
To see one or more icons as show in screenshots with information

# Current Behavior

What is the current behavior?
No icons appear

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
I believe it is a bug

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 Use Zorin 16.2
2. step 2 Install extension from gnome shell extensions
3. you get it... a placeholder appears, but no icons

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Nvidia-Settings Version (if used): 520.56.06
* Nvidia-smi version (if used):520.56.06
* Operating System: Zorin OS 16.2

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by deppy-v2** [comment]
![Screenshot from 2022-12-16 16-36-59](https://user-images.githubusercontent.com/116858174/208086635-746e0144-4c87-432f-b8a2-6636ed615dfe.png)
Please find the screenshot from taskbar attached

**Comment by derenv** [comment]
A couple questions:
- What version of ZorinOS are you using? i.e. core/lite/pro etc
- What version of gnome is your installation of ZorinOS using? (`gnome-shell --version` in the terminal)
- Which version of the extension was this?
- What theme are you using? The default one?
- Are there any relevant logs? (use `journalctl` in the terminal to see all logs, you're probably looking for a missing file/missing icon error)

Once i have this information i can have a go at reproducing the error in a VM.

NOTE: be aware that you can edit the content of issues rather than deleting them and making a new one.

**Comment by derenv** [comment]
If you are using the SMI provider (or the Optimus Bumblebee provider which is just an optimus call to SMI), the nvidia-settings button **does not show** (as it doesn't know if the nvidia-settings package is installed). This is expected behaviour.

**Comment by deppy-v2** [comment]
Thanks for writing back. Hope the following answers your questions:

    What version of ZorinOS are you using? i.e. core/lite/pro etc -Core
    What version of gnome is your installation of ZorinOS using? (gnome-shell --version in the terminal) -3.38.4
    Which version of the extension was this?  -8
    What theme are you using? The default one? - ZorinGrey-Dark
    Are there any relevant logs? (use journalctl in the terminal to see all logs, you're probably looking for a missing file/missing icon error) - Nothing

I am using the Nvidia SMI provider as predicted, but I had hoped to see some updating dashboard style icon.

**Comment by derenv** [comment]
> some updating dashboard style icon

Not sure i understand what you mean here, can you clarify?

**Comment by deppy-v2** [comment]
So, in the current state atleast for me, it is just a place holder for a menu (refer earlier attachment) which shows GPU stats when clicked. I would have wanted one or more of the parameters say temperature or utilization displayed and updated in  real time on taskbar to add real value.

**Comment by deppy-v2** [comment]
It works, perhaps better documentation is only needed. Thanks a lot for your help and time.
