### ISSUE TITLE
Gnome 43 and 44  support

### ISSUE THREAD

**Issue by braindotai** [ethanwharris/gnome-nvidia-extension#209]
Any future plans for releasing versions supported for Gnome 43 and 44? It's been months since I couldn't use this extension. :( 

Looking forward to it, better late than never.

**Comment by derenv** [comment]
The current master branch should work, but there aren't plans to release a new version on the extensions website yet.

**Comment by DawsonMyers** [comment]
I got the extension to work again by adding "43, 44" to the "shell-version" array in metadata.json file, then restarted gnome-shell (alt+F2, r). Is there some kind of hurdle in place that prevents uploading a new build with just these changes (which are already present in master) to the gnome extensions website? Then everyone could use it again without having to manually fix.

![2023-08-16-17:04:35_Selection_001](https://github.com/ethanwharris/gnome-nvidia-extension/assets/10068152/32e50476-3e63-4144-b747-bf4275c20c5e)

**Comment by derenv** [comment]
Waiting for upload by @ethanwharris, see #211
