### ISSUE TITLE
nvidia-settings doesn't work as intended on wayland

### ISSUE THREAD

**Issue by merajmasuk** [ethanwharris/gnome-nvidia-extension#210]
# Expected Behavior

The extension should work as it works on X11. Currently on X11 it displays GPU Utilization in percents, Temperature in Celsius, GPU memory usage in percents, fan speed and GPU wattage.

# Current Behavior

When selected `nvidia-settings` as a properties provider, following notification appears:

```
Execution of nvidia-settings -q GPUUtilization -q [GPU]/GPUCoreTemp -q UsedDedicatedGPUMemory -q TotalDedicatedGPUMemory -q GPUCurrentFanSpeed -t failed:: ERROR: Error resolving target specification '' (No targets match target specification), specified in query 'GPUUtilization'
```

# Failure Information

The failure is likely related to `nvidia-settings` support for Wayland, not a bug of the gnome extension itself. As trying to execute the query via cli works on X11 but not on Wayland.

```
nvidia-settings -q GPUUtilization -t

ERROR: Error resolving target specification '' (No targets match target specification), specified in query 'GPUUtilization'.
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable Wayland: `sudo nano /etc/gdm3/custom.conf`
2. Change to true `WaylandEnable=true`
3. Log out
4. Before logging back in, select `Pop with Wayland`.

## Context

* Nvidia-Settings Version: 510.47.03
* Nvidia-smi version (N/A): 525.105.17
* Operating System: Pop OS 22.04 LTS

## Failure Logs

```
$ journalctl -b 0 -g nvidia-settings
Apr 22 01:24:28 pop-os gnome-shell[24503]: error: Execution of nvidia-settings -q GPUUtilization -q [GPU]/GPUCoreTemp -q UsedDedicatedGPUMemory -q TotalDedicatedGPUMemory -q GPUCurrentFanSpeed -t failed:: ERROR: Error resolving target specification '' (No targets match target specification), specified in query 'GPUUtilization'.
```

**Comment by derenv** [comment]
This isn't something we can fix currently - see [the issue in the nvidia-settings repository](https://github.com/NVIDIA/nvidia-settings/issues/69)
