### ISSUE TITLE
Freeze for 0,2s each 2s on gnome-shell

### ISSUE THREAD

**Issue by Id2ndR** [ethanwharris/gnome-nvidia-extension#42]
I have upgrade to Gnome 3.26.2 (fedora 27) and now this extension froze gnome shell for 0,2s each 2s. I haven't encountered this trouble on fedora 26.
Disableing this extension allow the gnome shell to run smoothly. The trouble don't occur with _Nvidia GPU Temperature Indicator_ extension but this last extension only display temperature. 

Version : nvidia-settings-387.22-1.fc27.x86_64

**Comment by ethanwharris** [comment]
![0be72077-3687-4a7a-a5d8-baed589e6b35](https://user-images.githubusercontent.com/9592806/32722881-4efb90f6-c863-11e7-90d8-bf48396b9c6b.jpeg)

@Id2ndR thank you for your feedback! This seems to be related to instability in Fedora 27 / Gnome 3.26. (See screenshot). At the moment we have 3 calls to Nvidia-settings every 2 seconds. For whatever reason, these are taking a lot of time in Fedora 27. We’re working on getting this down to 1 call for the next version and having a configurable refresh rate also. Please look out for version 3 of the extension which will have these changes.
